openapi: "3.0.1"
info:
  title: "AI Code Quality Pipeline API"
  description: "API for the AI code qality Pipeline (AI-CQ Pipeline for short)."
  version: "1.0.0"
servers:
  - url: "https://syghr3kuse.execute-api.eu-central-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: ""
paths:
  /add-test-results:
    post:
      operationId: "addTestResults"
      responses:
        default:
          description: "Default response for POST /add-test-results"
      security:
        - origin-authorizer: []
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:233965294453:function:ai-cq-pipeline-add-tests-to-report-handler/invocations"
        connectionType: "INTERNET"
  /start-pipeline-run:
    post:
      operationId: "startPipeline"
      responses:
        default:
          description: "Default response for POST /start-pipeline-run"
      security:
        - origin-authorizer: []
      x-amazon-apigateway-integration:
        integrationSubtype: "StepFunctions-StartExecution"
        credentials: "arn:aws:iam::233965294453:role/APIGatewayStepFunctionsIntegration"
        requestParameters:
          Input: "$request.body"
          StateMachineArn: "arn:aws:states:eu-central-1:233965294453:stateMachine:ai-cq-pipeline-stepfunction"
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
components:
  securitySchemes:
    origin-authorizer:
      type: "apiKey"
      name: "X-Hub-Signature-256"
      in: "header"
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.X-Hub-Signature-256"
        authorizerUri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:233965294453:function:ai-cq-pipeline-authorizer/invocations"
        authorizerPayloadFormatVersion: "2.0"
        authorizerResultTtlInSeconds: 0
        type: "request"
        enableSimpleResponses: true
x-amazon-apigateway-importexport-version: "1.0"
